### ISSUE TITLE
Suggestion: Short Q&A section ?

### ISSUE THREAD

**Issue by wentout** [nodejs/package-maintenance#132]
I'd wish to ask if we can make short Q & A section in the repo?

For newcomers: maintainers and who wish to help.

Something answering questions:

**How can I get help if I'm package maintainer?**

**How can I give help, if I wish?**

Something with keys to easy understanding of what happens or milestones.

[Gantt Chart](https://en.wikipedia.org/wiki/Gantt_chart) is quite nice, but hard to generate.
Changelog format is also nice, in relation to summ of meetings discussions.

Sum of what is the current moment, or how to start investigation what happens here. For me it is clear how to learn from group issues, and I know it is hard for some of my acquitances.

And also, from the other side, seems that, for example I need guidance to make helpfull effort. It is another point, but it tightly related to that Q & A for me.

**Comment by Eomm** [comment]
I totally agree when you say that is "hard" and if we facilitate the opt-in more people will join us to help.

Maybe could this section be filled with more info after this analysis phase will end and some "dirty jobs" will start?

**Comment by wentout** [comment]
> ... after this analysis phase ...

Ah, yes, sure, I mean this too. Might be I hurried with this suggestion.
Anyway it will be hard to answer this questions right now.
Though, it might someone will try to make assumptions, may be me.

**Comment by mhdawson** [comment]
My hope is that we will end up with a concrete list of "jobs" (dirty or not) that people can help out with but I think it will take us some time to figure out how to build and maintain that list.  I think the idea in this issue: https://github.com/nodejs/package-maintenance/issues/131. Is one where somebody with time could start digging in though.  Key things from the discussion on 131 in the last meeting is that:

* It needs to be opt in(ie don't spam module owners with PRs unless they ask for them)
* Build a framework so that when we have change Y that is needed across the ecosystem we can use the framework to generate the required PRs
* We might be able to start with the buffer constructor problem. It may be partially addressed but not completely.

**Comment by wentout** [comment]
@mhdawson  @rxmarbles seems we've figured out with solution for this on the [last meeting 2019-03-11](https://github.com/nodejs/package-maintenance/issues/170). 

So I will close this, if you don't mind, may I?

**Comment by wentout** [comment]
No objections, closing.
