### ISSUE TITLE
Demo of CITGM work/Module Insights

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/package-maintenance#179]
IBM, as part of CloudNativeJS, has created some automation around Module testing across different LTS Node.js versions - https://modules.cloudnativejs.io. This work included extending and building a wrapper around CITGM, which I believe relates to https://github.com/nodejs/package-maintenance/issues/84 and https://github.com/nodejs/package-maintenance/issues/114. 

I'd like to demo what we have and how it works as a proof of concept, as it may help to determine some use cases/features of any future tools formed to solve pacakage maintenance problems. 

/cc @mhdawson

**Comment by wesleytodd** [comment]
Hey @BethGriggs, this looks very interesting, sorry I am so late to reply (I was checked out for a few months and am still finding things I didn't catch up on).  

It looks like you doing some testing for Express community modules, which is awesome!  I would love it if we could see more about the goals of this project and see how we can align that more with the testing and support strategy the Express core team currently has.

And for what this WG is doing, maybe we can find a way to built out a framework for different groups to contribute their test runs to a shared place so that any company, like IBM, who is doing CITGM style test runs can contribute back.

We should keep the WG conversation here, but if you would like to discuss this with the Express team, opening an issue on https://github.com/expressjs/discussions is the place to do it.  Thanks!

**Comment by dominykas** [comment]
Did this demo ever happen? I'd be curious to learn more.

**Comment by BethGriggs** [comment]
@dominykas - I found the meeting that the demo was in https://youtu.be/FO4PZj_WHjA?t=944
Happy to run through again in future. That project hasn't been active in the past few months, but I think there may be some value we can extract from it (such as building parts of it into a small usable CLI tool or adding some new features to `nodejs/citgm`)

**Comment by dominykas** [comment]
Thanks, I'll take a look!

**Comment by BethGriggs** [comment]
Closing as the demo happened and we've now managed to get the first set of test tooling requirements listed in https://github.com/nodejs/package-maintenance/issues/307#issuecomment-587010238
