### ISSUE TITLE
Express Triage meetings

### ISSUE THREAD

**Issue by gireeshpunathil** [nodejs/package-maintenance#293]
Looks like it makes sense to have a recurring meeting among the triage team members

@mhdawson - request you to schedule an initial one for 10 PM IST, 11.30 AM EST, 8.30 AM PST on Dec 6th, and ping / alert the known members.

Here is the rough agenda:

 - discuss the approach and best practices for triaging
 - discuss who is going to work on which repo
 - discuss on how to co-orinate engagements
 - discuss on future meetings: theme, date, time, frequency

**Comment by wesleytodd** [comment]
That is pretty quick, we need more lead time before we schedule these.  Could we set the first meeting for early in the new year?  That way we can spread the word, have a clear agenda and make sure everyone can come?

**Comment by mhdawson** [comment]
@wesleytodd we've had a few people want to understand how they can get involved.  This is mostly about having Gireesh get them up to speed on what he's already been done and avoid people working on the same thing.

@helio-frota, @ghinks, @BethGriggs  are three of the people in addition to myself who were hoping to get up to speed/co-ordinate as opposed just waiting until the new year.  

@wesleytodd do you think there needs to be more of an agenda than what Gireesh had in the issue:

 - discuss the approach and best practices for triaging
 - discuss who is going to work on which repo
 - discuss on how to co-ordinate engagements
 - discuss on future meetings: theme, date, time, frequency

We can wait if you think that's best but seems better to at least connect the interested people instead of waiting for another month.

**Comment by mhdawson** [comment]
@helio-frota, @ghinks, @BethGriggs does the proposed time on Friday work for you? If not then its a moot point anyway and we might as well agree on a time for January.

**Comment by wesleytodd** [comment]
I didn't really mean to object to the agenda (I should have removed that line from my comment).  That part looks good!  

I was more objecting to scheduling a meeting only 3-4 days in advance via a GH issue.  Sometimes I am over a week behind and just didn't want others like me to miss the meeting time on accident.  Having more lead time helps make sure everyone has a chance to schedule appropriately.

Also, I can attend that time, so if everyone pinged here responds and can attend I have no objections.

**Comment by BethGriggs** [comment]
I can make that time 🙂

**Comment by ghinks** [comment]
I can make this time too. But 3-4 days it tight. But in general Fridays are good as many folks have less meetings as it is a work from home day in many organizations.

**Comment by helio-frota** [comment]
LGTM :+1:

**Comment by wesleytodd** [comment]
Ok, sounds like we are on for tomorrow!

Could we add to the end of the agenda (only if we have time) to discuss what we might do for https://github.com/openjs-foundation/summit/issues/219?

**Comment by mhdawson** [comment]
@wesleytodd talking about #219 sounds like a great idea.

**Comment by mhdawson** [comment]
Its on the Node.js calendar: https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98%40group.calendar.google.com

and here is the zoom link:  https://zoom.us/j/431077278

**Comment by jonchurch** [comment]
This isn't on the Node.js calendar anymore. The triage group got set up, and some meetings were held with that group under Express' umbrella. I'm embarrassed to say I don't know if they're still going on over at Express, but I think this issue can be closed on our end.
