### ISSUE TITLE
overview of current initiatives, housekeeping, & other questions

### ISSUE THREAD

**Issue by boneskull** [nodejs/package-maintenance#428]
I'm trying to get involved in this group (and/or some of the `pkgjs` repos) but I don't have a high-level understanding of the current initiatives.

There is a ["roadmap" GitHub Project](https://github.com/nodejs/package-maintenance/projects/1) but I'm not sure if I should trust it.  I would expect "in progress" initiatives to be on the meeting agenda.  That project includes the following "in progress" initiatives:

- #84: there's [wiby](/pkgjs/wiby), but I'm not entirely sure it solves what #84 is asking for.
- #248: This has been open for over a year; unclear if it's still desired or if it is actually "in progress"
- #209: unclear on next steps; there were several pokes at a tool to help test the result of `npm pack` which (I think) both @ljharb and @wesleytodd [and myself](https://github.com/boneskull/packtester) have independently worked on, which attempts to solve part of the identified problem
- #280: unclear what's going on here

Other:

- The items with the [`good first issue` label](https://github.com/nodejs/package-maintenance/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) seem to mainly be requests for draft "guidance" documents.  Are they all still needed?  Are some in progress?
- How is work coordinated between here (e.g., a tracking issue) and the `pkgjs` org repos?  
- Is there a process for creating a new repo in the `pkgjs` org?  
- Is there a plan for promotion of the new tools created in the `pkgjs` org?  We may have good tools, but how do we get them in front of users?

While I'm sure some of these questions can be answered here, I'm going to guess that some of them are best discussed on a call, so I've added the `package-maintenance-agenda` label, because I can.

**Comment by mhdawson** [comment]
Discussing in the next call makes the most sense.

**Comment by dominykas** [comment]
> Is there a process for creating a new repo in the pkgjs org?

https://github.com/nodejs/package-maintenance/blob/main/Governance.md#adding-or-removing-repositories

**Comment by thescientist13** [comment]
> The items with the good first issue label seem to mainly be requests for draft "guidance" documents. Are they all still needed? Are some in progress?

This effort is mainly aimed at getting docs out of [this draft folder](https://github.com/nodejs/package-maintenance/tree/main/docs/drafts) and updated to reflect status in [the main Table of Contents](https://github.com/nodejs/package-maintenance/tree/main/docs#table-of-contents).  That issue is tracking each doc via a standalone issue.

In most cases the content is already in progress, and so this is mostly just a formality.  But all the ones not assigned are up for grabs and open to contributors.  👍

**Comment by thescientist13** [comment]
Coming out of our team meeting #430 , did a little housekeeping that we can review on tomorrow's meeting , as a way to try and bring a little order to things and hopefully aid in discoverability of is being worked on at any given time and what the key big ticket items are, so to speak.

- Created a [project for 2021](https://github.com/nodejs/package-maintenance/projects/3) and added issues with recent activity around them (basically anything that has come up in recent meetings).  I think in a way this can at least capture "work in progress" at a glance and help give a sense of progression of tasks.  I opted to just start this on 2021 for sake of convenience since, well, it's already December 2020 and a year seemed like a good enough range of time to track. (although could be broken down more granularly, like quarterly)
- Created three new milestones to capture related work showing up in our project board (descriptions within each)
  - [Draft Documentation Promotion](https://github.com/nodejs/package-maintenance/milestone/4)
  - [Support Levels](https://github.com/nodejs/package-maintenance/milestone/3)
  - [PkgJS Organization](https://github.com/nodejs/package-maintenance/milestone/5)

**Comment by mhdawson** [comment]
We had an in person session and @thescientist13 has added some structure. If you have more questions please re-open or reach out to one of us individually.
