### ISSUE TITLE
2022 promotion events

### ISSUE THREAD

**Issue by vostrik** [nodejs/package-maintenance#506]
Let's do some promo activities in Q1 2022:

  1. **Article**
    - Goals
    - Current Status
    - Tools and Documents
    - Open Questions and Next Steps
    - Call to Action: Join, Review and Contribute
  2. **Status Talk** (round table keynote)
    The same with the article
  3. **Round Table**
    1. Format: Online Event with questions from community
    2. Participants from:
       - Out Team
       - Supported Packages
       - Community Influencers / Open Source Leaders

**Comment by mhdawson** [comment]
A session at OpenJS World probably also makes sense as a 4th activity.

**Comment by ghinks** [comment]
I'll reach out and try to work with @vostrik on this.

**Comment by mhdawson** [comment]
Link to CPF info - https://openjsf.org/openjs-world/2022/01/10/call-for-papers-openjs-world-2022/

**Comment by thescientist13** [comment]
I wonder if we would want to submit lightning talks (if those are available) at OpenJS 2022 for some of the recent accomplishments from the team
- Documentation Promotion - #373 
- v0.1.0 / beta of the pkgjs action - https://github.com/pkgjs/action

Or maybe a consolidated talk for the WG as a whole, depending on how much content / material we want to share.

CFPs closes 2/14, fyi.

**Comment by mhdawson** [comment]
Note the CFP closes Feb 14.

**Comment by vostrik** [comment]
I can submit a paper to OpenJS World. But I have a few questions:
1. Should I submit a paper from my name as primary speaker or submit for another team member?
2. We can submit up to 2 delegates. We want to submit one or two speakers?
3. We want to submit regular speech or panel discussion?

**Comment by mhdawson** [comment]
> Should I submit a paper from my name as primary speaker or submit for another team member? 
> We can submit up to 2 delegates. We want to submit one or two speakers?

This all depends on who is interested in being part of the talk . If somebody else volunteers then you might do a joint submission, otherwise you could submit as the only speaker. 

I think several of the other team members had other submissions they were going to make. That's the case I'm in and I'd be happy to have you submit a talk on behalf of the team.

**Comment by dominykas** [comment]
Looks like the OpenJS World deadline has been extended: https://twitter.com/openjsf/status/1492300415542738945

**Comment by vostrik** [comment]
Thx, i submitted the talk!

**Comment by mhdawson** [comment]
@vostrik great to hear.

**Comment by vostrik** [comment]
General topics will be:
- Goals
- Current Status
- Tools and Documents
- Open Questions and Next Steps
- Call to Action: Join, Review and Contribute

**Comment by ruyadorno** [comment]
We discussed this in [today's meeting](https://github.com/nodejs/package-maintenance/issues/538) and agreed to submit a proposal to host a Package Maintenance Working Group session in the [upcoming Collaborator Summit in Dublin](https://www.eventbrite.com/e/openjs-foundation-collaborator-summit-dublin-tickets-410575531467) which will definitely help promote and raise awareness of the WG among collaborators present there.

In order to get things going I went ahead and submitted the proposal, ref: https://github.com/openjs-foundation/summit/issues/337. Heads up to @nodejs/package-maintenance folks, let me know if anyone is going to be there in-person and would like to facilitate as well, I can add your name to the proposal 😊

**Comment by mhdawson** [comment]
I'm going to close this as it is the end of 2022 and we can create a new issue for 2023
